# Generated by Django 4.1.3 on 2023-02-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number_of_routes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
